### ISSUE TITLE
Feature Request: Configurable sigmakee server instance

### ISSUE THREAD

**Issue by alexander-gabriel** [ontologyportal/SUMOjEdit#3]
I would suggest using the Jedit configuration capability since relying on the sigmakee config.xml would introduce a dependency to have that installed locally.

**Comment by apease** [comment]
I'm afraid I hadn't understood your questions earlier about this.  Sigma does indeed have to be installed and called locally.  SUMOjEdit does not have the capability to call Sigma on a remote server.  The sigmakee.jar, config.xml and all .kif files must be available on the same machine where you are running SUMOjEdit
