### ISSUE TITLE
Feature Request: Standalone build process

### ISSUE THREAD

**Issue by alexander-gabriel** [ontologyportal/SUMOjEdit#4]
Detangeling the build process from that of sigmakee allows installing one without the other.

This reduces maintenance and the barrier of entry for organisations, where one sigma server could be used by the whole team.

Sigma .jar files could be copied over manually, or could even be provided in the sigmakee repository for download.

**Comment by apease** [comment]
This use case doesn't fit with what Sigma and SUMOjEdit were developed for.  If there's a "read-only" scenario then one can use Sigma via the browser interface.  But the SUMOjEdit editor was designed for a use case where a user is making changes to files.  So, those changes must be reflected in the files Sigma has access to.  We don't have any sort of distributed collaboration system.  The general use case is that users change files locally, upload them to GitHub (or maybe some local fork on their own GitHub/GitLab etc), and then all users check out those updated files to their own system.
